.PHONY: help
help:  ## Display this help message.
	@egrep -h '\s##\s' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-30s\033[0m %s\n", $$1, $$2}'

.PHONY: install-tools
install-tools: ## Installs the tools as the git pre-commit hook for this repo as well a dependency tools.
	@which pre-commit > /dev/null || echo "pre-commit not installed, see https://pre-commit.com/#install"
	@pre-commit install --install-hooks

.PHONY: lint
lint: ## Runs linters via pre-commit.
	@pre-commit run -v --all-files