package compose

import (
	"os"
	"path/filepath"
	"testing"

	serviceinfo "github.com/sid-technologies/pilum/lib/service_info"

	"github.com/stretchr/testify/require"
)

func TestServiceNameToEnvVar(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{"simple", "api", "API"},
		{"with dash", "auth-service", "AUTH"},
		{"with service suffix", "authentication-service", "AUTHENTICATION"},
		{"no service suffix", "gateway", "GATEWAY"},
		{"underscores", "my-cool-app", "MY_COOL_APP"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.expected, serviceNameToEnvVar(tt.input))
		})
	}
}

func TestWriteEnvFile(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	envPath := filepath.Join(dir, ".env.example")

	services := []serviceinfo.ServiceInfo{
		{Name: "auth-service"},
		{Name: "gateway"},
	}
	ports := map[string]int{
		"auth-service": 8080,
		"gateway":      8081,
	}

	err := WriteEnvFile(envPath, services, ports)
	require.NoError(t, err)

	content, err := os.ReadFile(envPath)
	require.NoError(t, err)

	s := string(content)
	require.Contains(t, s, "VITE_AUTH_API_URL=http://localhost:8080/api/v1")
	require.Contains(t, s, "VITE_GATEWAY_API_URL=http://localhost:8081/api/v1")
	require.Contains(t, s, "Generated by: pilum compose")
}
