package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sid-technologies/pilum/lib/errors"
	serviceinfo "github.com/sid-technologies/pilum/lib/service_info"
)

// WriteEnvFile generates a .env template with VITE_*_API_URL entries for each service.
func WriteEnvFile(envPath string, services []serviceinfo.ServiceInfo, ports map[string]int) error {
	var b strings.Builder
	b.WriteString("# Environment Configuration\n")
	b.WriteString("# Generated by: pilum compose\n")
	b.WriteString("# Copy to .env.local and fill in your values\n\n")

	b.WriteString("# Backend Services\n")
	b.WriteString("# Ports are assigned alphabetically by service name (deterministic).\n")
	b.WriteString("# Re-run `pilum compose` to regenerate if services are added/removed.\n\n")

	for _, svc := range services {
		port, ok := ports[svc.Name]
		if !ok {
			continue
		}
		envName := serviceNameToEnvVar(svc.Name)
		b.WriteString(fmt.Sprintf("VITE_%s_API_URL=http://localhost:%d/api/v1\n", envName, port))
	}

	dir := filepath.Dir(envPath)
	if dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return errors.Wrap(err, "error creating env file directory")
		}
	}

	return os.WriteFile(envPath, []byte(b.String()), 0o644)
}

// serviceNameToEnvVar converts a service name to an env var prefix.
// e.g., "authentication-service" -> "AUTHENTICATION"
func serviceNameToEnvVar(name string) string {
	envName := strings.ToUpper(name)
	envName = strings.ReplaceAll(envName, "-", "_")
	envName = strings.TrimSuffix(envName, "_SERVICE")
	return envName
}
